apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
data:
  file: |
    <html>
    <head><title>Homework App</title></head>
    <body>
      <h1>🎉 Добро пожаловать в {{ .Values.app.name }}!</h1>
      <p>Этот контент управляется через ConfigMap.</p>
      <ul>
        <li><a href="http://{{ .Values.httproute.hostname }}/index.html">Главная</a></li>
        <li><a href="http://{{ .Values.httproute.hostname }}/homepage">Домашняя</a></li>
        <li><a href="http://{{ .Values.httproute.hostname }}/metrics.html">Метрики кластера</a></li>
      </ul>
    </body>
    </html>
