apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: homework
  name: metrics-reader
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io/v1beta1"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]