# Глобальные
namespace: homework
nameOverride: ""
fullnameOverride: ""

# Приложение
app:
  name: homework-app
  labels:
    app: homework-app

# Реплики
replicas: 3

# Стратегия обновления
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

# Образы
images:
  nginx:
    repository: nginx
    tag: "latest"
    pullPolicy: IfNotPresent
  initContainer:
    repository: busybox
    tag: "latest"
    pullPolicy: IfNotPresent
  metricsFetcher:
    repository: alpine
    tag: "latest"
    pullPolicy: IfNotPresent

# Имена контейнеров
containers:
  nginx:
    name: homework-nginx
    port: 8000
  initContainer:
    name: init-container
  metricsFetcher:
    name: metrics-fetcher

# Service
service:
  name: homework-service
  type: ClusterIP
  port: 8000
  targetPort: 8000

# Gateway
gateway:
  className: traefik
  name: homework-gateway
  port: 8000
  controllerName: traefik.io/gateway-controller

# HTTPRoute
httproute:
  name: homework-app-route
  hostname: homework.otus

# ConfigMaps
configMaps:
  nginx:
    name: nginx-config
  app:
    name: homework-config

# Storage
storage:
  storageClass:
    name: homework-sc-hostpath
    provisioner: k8s.io/minikube-hostpath
    reclaimPolicy: Retain
    isDefault: true
  pvc:
    name: homework-pvc
    size: 100Mi
    accessMode: ReadWriteOnce

# ServiceAccounts / RBAC
serviceAccounts:
  monitoring:
    name: monitoring
  cd:
    name: cd
    createToken: true

rbac:
  clusterRole:
    name: metrics-reader
  roleBindings:
    monitoring:
      name: monitoring-read-metrics
    cdAdmin:
      name: cd-admin

# Probes
probes:
  enabled: true
  readiness:
    httpGet:
      path: /index.html
    initialDelaySeconds: 5
    periodSeconds: 5
  liveness:
    enabled: false
    httpGet:
      path: /index.html
    initialDelaySeconds: 10
    periodSeconds: 10

# Resources
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# NodeSelector
nodeSelector:
  homework: "true"

# Redis
redis:
  enabled: true
  image:
    repository: bitnamilegacy/redis
    tag: "7.4.2-debian-12-r4"
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  volumePermissions:
    enabled: false

# Traefik
traefik:
  enabled: true
  providers:
    kubernetesGateway:
      enabled: true
  gateway:
    enabled: false
  gatewayClass:
    enabled: false
  service:
    type: LoadBalancer
  nodeSelector:
    homework: "true"
  ports:
    web:
      port: 8000
    websecure:
      port: 8443
  additionalArguments:
    - "--global.checkNewVersion=false"
    - "--global.sendAnonymousUsage=false"
    - "--metrics.prometheus=true"
    - "--metrics.prometheus.entrypoint=metrics"

# MetricServer
metrics-server:
  enabled: true
  args:
    - --secure-port=10250
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
    - --kubelet-insecure-tls