releases:
  # ─── PROD: 5 брокеров, Kafka 3.5.2, SASL_PLAINTEXT ───
  - name: kafka-prod
    namespace: prod
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: "25.3.5"
    createNamespace: true
    values:
      - global:
          imageRegistry: mirror.gcr.io
          security:
            allowInsecureImages: true
        controller:
          replicaCount: 5
        image:
          tag: 3.5.2-debian-12-r0
        listeners:
          client:
            protocol: SASL_PLAINTEXT
          interbroker:
            protocol: SASL_PLAINTEXT
          controller:
            protocol: SASL_PLAINTEXT
        sasl:
          enabledMechanisms: plain
          interBrokerMechanism: plain
          controllerMechanism: plain
          jaas:
            clientUsers:
              - admin
            clientPasswords:
              - adminpassword
        persistence:
          enabled: true
          size: 1Gi

        securityContext:
          runAsUser: 1000
          fsGroup: 2000
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        crds:
          create: true

  # ─── DEV: 1 брокер, Kafka последняя версия (4.0), PLAINTEXT, без авторизации ───
  - name: kafka-dev
    namespace: dev
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: "32.4.3"
    createNamespace: true
    values:
      - global:
          imageRegistry: mirror.gcr.io
          security:
            allowInsecureImages: true
        controller:
          replicaCount: 1
        image:
          tag: 4.0.0-debian-12-r10
        listeners:
          client:
            protocol: PLAINTEXT
          interbroker:
            protocol: PLAINTEXT
          controller:
            protocol: PLAINTEXT
        persistence:
          enabled: false

        securityContext:
          runAsUser: 1000
          fsGroup: 2000
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        crds:
          create: true