releases:
    # ─── PROD: 3 controller + 5 broker, Kafka 3.5.2, SASL_PLAINTEXT ───
  - name: kafka-prod
    namespace: prod
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: "25.3.5"
    createNamespace: true
    values:
      - global:
          security:
            allowInsecureImages: true
        controller:
          replicaCount: 1
          automountServiceAccountToken: true
        broker:
          replicaCount: 5
          persistence:
            size: 1Gi
          automountServiceAccountToken: true
        image:
          registry: docker.io
          repository: bitnamilegacy/kafka
          tag: "3.5.2-debian-11-r10"
        defaultInitContainers:
          prepareConfig:
            image:
              registry: docker.io
              repository: bitnamilegacy/kafka
              tag: "3.5.2-debian-11-r10"
        volumePermissions:
          enabled: true
          image:
            registry: docker.io
            repository: bitnamilegacy/os-shell
            tag: "12-debian-12-r51"
        kraft:
          enabled: true
          clusterId: "MkU3OEVBNTcwNTJENDM2Qk"
        zookeeper:
          enabled: false
        listeners:
          client:
            protocol: SASL_PLAINTEXT
          interbroker:
            protocol: SASL_PLAINTEXT
          controller:
            protocol: SASL_PLAINTEXT
        sasl:
          enabledMechanisms: plain
          interBrokerMechanism: plain
          controllerMechanism: plain
          jaas:
            clientUsers:
              - admin
            clientPasswords:
              - adminpassword
        persistence:
          enabled: true
          size: 8Gi
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi

  # ─── DEV: 1 брокер, Kafka 4.0.0, PLAINTEXT, без авторизации ───
  - name: kafka-dev
    namespace: dev
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: "32.4.3"
    createNamespace: true
    values:
      - global:
          security:
            allowInsecureImages: true
        controller:
          replicaCount: 1
          automountServiceAccountToken: true
          persistence:
            enabled: false
        broker:
          replicaCount: 1
          persistence:
            enabled: false
          automountServiceAccountToken: true
        image:
          registry: docker.io
          repository: bitnamilegacy/kafka
          tag: "4.0.0-debian-12-r10"
        defaultInitContainers:
          prepareConfig:
            image:
              registry: docker.io
              repository: bitnamilegacy/kafka
              tag: "4.0.0-debian-12-r10"
          volumePermissions:
            enabled: true
            image:
              registry: docker.io
              repository: bitnamilegacy/os-shell
              tag: "12-debian-12-r51"
        kraft:
          enabled: true
          clusterId: "MkU3OEVBNTcwNTJENDM2Qk"
        zookeeper:
          enabled: false
        listeners:
          client:
            protocol: PLAINTEXT
          interbroker:
            protocol: PLAINTEXT
          controller:
            protocol: PLAINTEXT
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
