apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-config
  namespace: homework
data:
  file: |
    <html>
    <head><title>Homework App</title></head>
    <body>
      <h1>🎉 Добро пожаловать в homework-app!</h1>
      <p>Этот контент управляется через ConfigMap.</p>
      <ul>
        <li><a href="/index.html">Главная</a></li>
        <li><a href="/metrics.html">Метрики кластера</a></li>
      </ul>
    </body>
    </html>