apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: homework
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator-sa
      containers:
        - name: mysql-operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: "homework"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi