apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.49.2:8443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: homework
    user: cd
  name: homework-cd
current-context: homework-cd
kind: Config
users:
- name: cd
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkEyLXlTdzdnNEFleHdwNzBFVlpMU0xLWGZ3cWxZS2NkTEFzQ2ZFNWRXSFEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzg5NTAwMDUxLCJpYXQiOjE3ODk0MTM2NTEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZTc0OWFiYmYtYjk0ZS00MmMwLWExNjgtZmIyNDgwNmU5MzlmIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6ImQ3MDQyZjJlLTAxODUtNDQwNS1hYTVhLTg4OWUwMTVkMjY3NCJ9fSwibmJmIjoxNzg5NDEzNjUxLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.oqGRmmxJ7bjrI9wggSev6CAv5kN3WeSTl34GPUyFSbJGyQeuhWknXp7Nfg5ZQjf28eZM5bEwckQeVaJ_y2rWZSCYaTD0SVvGvN2etZ_FbtLQFdVB5wWH-sG3en61ekzlaZXvslw_nBFQyVK0zdKRlh5yTS9kmtEx6DleyMXALQrtX_oF3dpjyPQcnb7_ewJxdJ86abpYzos0FcxSL-EZ9U8P65B7qNZCH2fsdcZwYeVEwmIbxlrAbW9Jd_AMSWstNusKXYzI-lVBQJ5WHKj4gDi5SMCgrdZ5ECefkwWKmd-riiEGxUlqb3EzEsc9r0zsU7b644JQ1z5YcaP0sfXM4Q
