apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: homework
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator-sa
      containers:
        - name: operator
          image: docker.io/roflmaoinmysoul/mysql-operator:1.0.0
          imagePullPolicy: IfNotPresent