apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework-pod
  template:
    metadata:
      labels:
        app: homework-pod
    spec:
      volumes:
        - name: homework-volume
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', 'mkdir -p /init && echo "<html><body><h1>Homework Assignment #2 - Morozov N.N.</h1><p>This file was created by init container busybox</p></body></html>" > /init/index.html']
          volumeMounts:
            - name: homework-volume
              mountPath: /init
      containers:
        - name: web-server
          image: nginx:alpine
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: homework-volume
              mountPath: /homework
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "rm -f /homework/index.html"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            exec:
              command:
                - cat
                - /homework/index.html
            initialDelaySeconds: 5
            periodSeconds: 10
      nodeSelector:
        homework: "true"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1