apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.nginx.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen {{ .Values.containers.nginx.port }};
        server_name localhost;

        location / {
            root /homework;
            index index.html;
        }

        location /conf/ {
            alias /homework/conf/;
            default_type text/html;
            add_header Content-Type "text/html; charset=utf-8" always;
        }
    }
