---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.monitoring.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.cd.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
---
{{- if .Values.serviceAccounts.cd.createToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccounts.cd.name }}-token
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccounts.cd.name }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
