apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storage.storageClass.isDefault | quote }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
provisioner: {{ .Values.storage.storageClass.provisioner }}
reclaimPolicy: {{ .Values.storage.storageClass.reclaimPolicy }}
volumeBindingMode: Immediate
