repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    namespace: prod
    createNamespace: true
    chart: bitnami/kafka
    version: 29.3.14
    values:
      - values-prod.yaml

  - name: kafka-dev
    namespace: dev
    createNamespace: true
    chart: bitnami/kafka
    version: 29.3.14
    values:
      - values-dev.yaml