image:
  repository: soldevelo/kafka
  tag: 3.7.1

global:
  security:
    allowInsecureImages: true

persistence:
  enabled: false

listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT

auth:
  enabled: false

controller:
  replicaCount: 1
